jobs:
  cache-gremlin-server-docker-image:
    name: cache gremlin-server docker image
    needs: smoke
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Generate Gremlin Server Base
      run: 'mvn clean install -pl gremlin-server -DskipTests -DskipIntegrationTests=true
        -Dci -am

        '
      working-directory: .
    - continue-on-error: true
      name: Save Docker image
      run: docker save --output gremlin-server.tar tinkerpop/gremlin-server
      working-directory: ./gremlin-server
    - continue-on-error: true
      id: gremlin-server-test-docker-image
      uses: actions/cache@v4
      with:
        key: ${{ github.sha }}
        path: './gremlin-server/*

          ~/.m2/repository/org/apache/tinkerpop/*

          '
    timeout-minutes: 10
  dotnet:
    name: .NET
    needs: cache-gremlin-server-docker-image
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Set up .NET 8.0.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - continue-on-error: true
      id: gremlin-server-test-docker-image
      name: Get Cached Server Base Image
      uses: actions/cache@v4
      with:
        key: ${{ github.sha }}
        path: './gremlin-server/*

          ~/.m2/repository/org/apache/tinkerpop/*

          '
    - continue-on-error: true
      name: Load Docker Image
      run: docker load --input gremlin-server.tar
      working-directory: ./gremlin-server
    - continue-on-error: true
      name: Build with Maven
      run: 'touch gremlin-dotnet/src/.glv

        touch gremlin-dotnet/test/.glv

        mvn clean install -pl -:gremlin-javascript,-:gremlin-python,-:gremlint -q
        -DskipTests -Dci

        mvn verify -pl :gremlin-dotnet,:gremlin-dotnet-tests -P gremlin-dotnet

        '
    timeout-minutes: 20
  go:
    name: go
    needs: cache-gremlin-server-docker-image
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    - continue-on-error: true
      id: gremlin-server-test-docker-image
      name: Get Cached Server Base Image
      uses: actions/cache@v4
      with:
        key: ${{ github.sha }}
        path: './gremlin-server/*

          ~/.m2/repository/org/apache/tinkerpop/*

          '
    - continue-on-error: true
      name: Load Docker Image
      run: docker load --input gremlin-server.tar
      working-directory: ./gremlin-server
    - continue-on-error: true
      name: Build with Maven
      run: 'touch gremlin-go/.glv

        mvn clean install -pl -:gremlin-python,-:gremlin-javascript,-:gremlin-dotnet,-:gremlin-dotnet-source,-:gremlin-dotnet-tests
        -q -DskipTests -Dci

        mvn verify -pl :gremlin-go

        '
      working-directory: .
    - continue-on-error: true
      name: Upload to Codecov
      uses: codecov/codecov-action@v4
      with:
        working-directory: ./gremlin-go
    - continue-on-error: true
      name: Go-Vet
      run: go vet ./...
      working-directory: ./gremlin-go
    timeout-minutes: 20
  gremlin-console:
    name: gremlin-console
    needs: smoke
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Build with Maven
      run: 'touch gremlin-python/.glv

        mvn clean install -pl -:gremlin-javascript,-:gremlin-python,-gremlin-dotnet,-:gremlin-dotnet-source,-:gremlin-dotnet-tests,-:gremlint
        -q -DskipTests -Dci

        mvn verify -pl :gremlin-console -DskipTests -DskipIntegrationTests=false

        '
    timeout-minutes: 20
  gremlin-driver:
    name: gremlin-driver
    needs: cache-gremlin-server-docker-image
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Build with Maven
      run: 'mvn clean install -pl -:gremlin-javascript,-gremlin-dotnet,-:gremlin-dotnet-source,-:gremlin-dotnet-tests,-:gremlint
        -q -DskipTests -Dci

        mvn verify -pl gremlin-driver -DskipIntegrationTests=false

        '
    timeout-minutes: 20
  gremlin-server-default:
    name: gremlin-server default
    needs: smoke
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Build with Maven
      run: 'mvn clean install -pl -:gremlin-javascript,-:gremlin-python,-gremlin-dotnet,-:gremlin-dotnet-source,-:gremlin-dotnet-tests,-:gremlint
        -q -DskipTests -Dci

        mvn verify -pl :gremlin-server -DskipTests -DskipIntegrationTests=false -DincludeNeo4j

        '
    timeout-minutes: 45
  gremlin-server-unified:
    name: gremlin-server unified
    needs: smoke
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Build with Maven
      run: 'mvn clean install -pl -:gremlin-javascript,-:gremlin-python,-gremlin-dotnet,-:gremlin-dotnet-source,-:gremlin-dotnet-tests,-:gremlint
        -q -DskipTests -Dci

        mvn verify -pl :gremlin-server -DskipTests -DskipIntegrationTests=false -DincludeNeo4j
        -DtestUnified=true

        '
    timeout-minutes: 45
  java-jdk11:
    name: mvn clean install - jdk11
    needs: smoke
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Build with Maven
      run: mvn clean install -pl -:gremlin-javascript,-:gremlin-dotnet-source,-:gremlin-dotnet-tests,-:gremlin-go,-:gremlin-python
        -Dci --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
        -Dcoverage
    - continue-on-error: true
      name: Upload to Codecov
      uses: codecov/codecov-action@v4
      with:
        directory: ./gremlin-tools/gremlin-coverage/target/site
    timeout-minutes: 45
  java-jdk17:
    name: mvn clean install - jdk17
    needs: smoke
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Build with Maven
      run: mvn clean install -pl -:gremlin-javascript,-:gremlin-dotnet-source,-:gremlin-dotnet-tests,-:gremlin-go,-:gremlin-python
        -Dci --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    timeout-minutes: 45
  java-jdk8:
    name: mvn clean install - jdk8
    needs: smoke
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '8'
    - continue-on-error: true
      name: Build with Maven
      run: mvn clean install -pl -:gremlin-javascript -Dci --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    timeout-minutes: 45
  javascript:
    name: javascript
    needs: cache-gremlin-server-docker-image
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      id: gremlin-server-test-docker-image
      if: matrix.os == 'ubuntu-latest'
      name: Get Cached Server Base Image
      uses: actions/cache@v4
      with:
        key: ${{ github.sha }}
        path: './gremlin-server/*

          ~/.m2/repository/org/apache/tinkerpop/*

          '
    - continue-on-error: true
      name: Load Docker Image
      run: docker load --input gremlin-server.tar
      working-directory: ./gremlin-server
    - continue-on-error: true
      name: Build with Maven
      run: 'mvn clean install -pl -:gremlin-python,-gremlin-dotnet,-:gremlin-dotnet-source,-:gremlin-dotnet-tests
        -q -DskipTests -Dci

        mvn verify -pl :gremlin-javascript,:gremlint

        '
    strategy:
      matrix:
        os:
        - ubuntu-latest
    timeout-minutes: 15
  neo4j-gremlin:
    name: neo4j-gremlin
    needs: smoke
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Build with Maven
      run: 'mvn clean install -pl -:gremlin-javascript,-:gremlin-python,-gremlin-dotnet,-:gremlin-dotnet-source,-:gremlin-dotnet-tests
        -q -DskipTests -Dci

        mvn verify -pl :neo4j-gremlin -DincludeNeo4j

        '
    timeout-minutes: 20
  python:
    name: python
    needs: cache-gremlin-server-docker-image
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    - continue-on-error: true
      name: Build with Maven
      run: 'touch gremlin-python/.glv

        mvn clean install -pl -:gremlin-javascript,-gremlin-dotnet,-:gremlin-dotnet-source,-:gremlin-dotnet-tests,-:gremlint
        -q -DskipTests -Dci

        mvn verify -pl gremlin-python

        '
    timeout-minutes: 20
  smoke:
    name: smoke
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Build with Maven
      run: mvn clean install -DskipTests -Dci --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    timeout-minutes: 10
  spark-core:
    name: spark core
    needs: smoke
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      if: runner.os == 'Windows'
      name: Build with Maven Windows
      run: 'mvn clean install -pl -:gremlin-javascript,-:gremlin-python,-gremlin-dotnet,-:gremlin-dotnet-source,-:gremlin-dotnet-tests,-:gremlint
        -q -DskipTests -DskipImageBuild -Dci

        '
    - continue-on-error: true
      if: runner.os == 'Linux'
      name: Build with Maven Ubuntu
      run: 'mvn clean install -pl -:gremlin-javascript,-:gremlin-python,-gremlin-dotnet,-:gremlin-dotnet-source,-:gremlin-dotnet-tests,-:gremlint
        -q -DskipTests -Dci

        mvn verify -pl :spark-gremlin -DskipTests -DskipIntegrationTests=false ''-Dit.test=*IntegrateTest,!SparkGryoSerializerGraphComputerProcessIntegrateTest''

        '
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
    timeout-minutes: 45
  spark-gryo:
    name: spark gryo
    needs: smoke
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      if: runner.os == 'Windows'
      name: Build with Maven Windows
      run: 'mvn clean install -pl -:gremlin-javascript,-:gremlin-python,-gremlin-dotnet,-:gremlin-dotnet-source,-:gremlin-dotnet-tests,-:gremlint
        -q -DskipTests -DskipImageBuild -Dci

        '
    - continue-on-error: true
      if: runner.os == 'Linux'
      name: Build with Maven Ubuntu
      run: 'mvn clean install -pl -:gremlin-javascript,-:gremlin-python,-gremlin-dotnet,-:gremlin-dotnet-source,-:gremlin-dotnet-tests,-:gremlint
        -q -DskipTests -Dci

        mvn verify -pl :spark-gremlin -DskipTests -DskipIntegrationTests=false -Dit.test=SparkGryoSerializerGraphComputerProcessIntegrateTest

        '
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
    timeout-minutes: 45
name: build-test
on:
  repository_dispatch:
    types: trigger-ga___build-test.yml
